apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fowqbg8cr-go
  janus-idp.io/tekton: fowqbg8cr-go
  backstage.io/kubernetes-id: fowqbg8cr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fowqbg8cr-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
