apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fowqbg8cr-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fowqbg8cr-go 
  name: fowqbg8cr-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fowqbg8cr-go 
