apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: fowqbg8cr-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:eba59a9f0483468789b9f8a6fc29e464eafd5f08@sha256:0d99e79571fb376b754e3bdfe0f43c7f8613ef7554ea212acd35f1f335f83e0a
          name: container-image
